version: "3.8"

services:
  database:
    image: postgres:15
    container_name: lms-db
    restart: always
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: lms
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  directus:
    image: directus/directus:latest
    container_name: lms-directus
    restart: always
    ports:
      - "8055:8055"
    environment:
      KEY: "random-key"
      SECRET: "super-secret"
      ADMIN_EMAIL: "adminlms@admin.com"
      ADMIN_PASSWORD: "passwordlms"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "lms"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      PUBLIC_URL: "http://localhost:8055"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "http://localhost:5173"

      
    volumes:
      - ./directus/extensions:/directus/extensions
      - directus_uploads:/directus/uploads
    depends_on:
      - database
volumes:
  db_data:
  directus_uploads:
